#
# Home Assistant Automation Blueprint
#
# Sends two notifications on speaker to close a window or door after opening it, 
# if the temperature outside is below a certain degree. 
#
# Revision 
# Viskor Bouacida, feb. 2022
#
# base from https://github.com/home-IoT/hass-blueprints/blob/main/reminder_to_close_window.yaml
#

blueprint:
  name: Speaker to Close a Window 
  description: speak to close windows if it is cold outside
  domain: automation
  input: 
    contact_sensor: 
      name: Contact Sensor
      description: 'The window or door sensor that triggers the automation.'
      selector: 
        entity:
          domain: binary_sensor
    first_timer:
      name: 'First timer'
      description: 'The first notification timer (in minutes).'
      default: 10
      selector: 
        number:
          min: 1
          step: 1
          max: 60
          mode: slider
    second_timer:
      name: 'Second timer'
      description: 'The second notification timer (in minutes).'
      default: 15
      selector: 
        number:
          min: 1
          step: 1
          max: 60
          mode: slider
    temperature:
      name: 'Temperature'
      description: 'The outside temperature below which the notification should be sent.'
      default: 20
      selector: 
        number:
          min: 0
          step: 1
          max: 25
          mode: slider
    speaker:
      name: speaker to no5tify
      description: >
        The device to receive the notification; it needs to run the official 
        Home Assistant app to receive notifications.
      selector: 
        entity:
          domain: media_player
      

# We will have two triggers, for the two different reminders. 
# However, a reminder will be ignored if the door or window is already closed by then. 
trigger:
- platform: state
  entity_id: !input contact_sensor
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: !input first_timer
    seconds: 0
- platform: state
  entity_id: !input contact_sensor
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: !input second_timer
    seconds: 0

# Two conditions:
# 1. The door or window should still be open. 
# 2. The temperature reading must be below the set value. 
condition:
- condition: state
  entity_id: !input contact_sensor
  state: 'on'
- condition: numeric_state
  entity_id: weather.pihome
  attribute: temperature
  below: !input temperature

# Send a notification to the speaker device. 
action:
- service: tts.google_translate_say
  data:
    entity_id: !input speaker
    message: "Que la force soit avec toi {{trigger.to_state.attributes.friendly_name}}"
    language: "fr"
  

mode: single
