blueprint:
  name: VK - Window open TTS announcer v3
  description: speak to close windows if it is cold outside
  domain: automation
  input:
    window_entity:
      name: window Sensor
      description: Entity that causes announcement
      selector:
        entity:
          domain: binary_sensor
          device_class: window
    speaker_target:
      name: Speaker
      description: Entity to announce event on
      selector:
        target:
          entity:
            domain: media_player
    announcement_message:
      name: Announcement message
      description: What to say when window is opened
    final_message:
      name: Final message
      description: What to say when window is closed  
    cooldown:
      name: Announcement cooldown
      description: The minimum time needed in between announcements
      default: 10
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds
    temperature:
      name: 'Temperature'
      description: 'The outside temperature below which the notification should be sent.'
      default: 20
      selector: 
        number:
          min: 0
          step: 1
          max: 25
          mode: slider

mode: single

trigger:
  platform: state
  entity_id: !input window_entity
  from: "off"
  to: "on"

condition:
  - condition: numeric_state
    entity_id: weather.maison
    attribute: temperature
    below: !input temperature

action:
  - alias: Repeat the sequence UNTIL the window is closed
    repeat:
      sequence:
        - delay: !input cooldown 
        - service: tts.google_translate_say
          target: !input speaker_target
          data:
            message: !input announcement_message
      until:
        - condition: state
          entity_id: !input window_entity
          state: 'off'
  - service: tts.google_translate_say
    target: !input speaker_target
    data:
      message: !input final_message
