blueprint:
  name: VK Dev - Calendar To Hub v9
  description: Basé sur https://www.home-assistant.io/integrations/google/ Envois de musique sur google hub
  domain: automation
  input:
    calendar_sensor:
      name: Calendrier à observer
      selector:
        entity:
          domain: calendar
    start_time:
      name: Heure de début d'événement doit etre apres 
      description: Time action should start
      selector:
        time:
    end_time:
      name: Heure de début d'événement doit etre apres 
      description: Time action should stop
      selector:
        time:
    weekday:
      name: Day of the week to use the Automation
      default: [mon, tue, wed, thu, fri, sat, sun]
      selector:
        select:
          options:
          - label: Monday
            value: mon
          - label: Tuesday
            value: tue
          - label: Wednesday
            value: wed
          - label: Thursday
            value: thu
          - label: Friday
            value: fri
          - label: Saturday
            value: sat
          - label: Sunday
            value: sun
          custom_value: false
          multiple: true
    timebefore:
      name: Timer for calendar
      description: The minimum time needed in between announcements
      default: 1:00:00
      selector:
        duration:
          hours: 1
          minutes: 30
    speaker_target:
      name: Speaker
      description: Entity to announce event on
      selector:
        target:
          entity:
            domain: media_player
    
mode: single

trigger:
  - platform: calendar
    event: start
    offset: !input timebefore
    entity_id: !input calendar_sensor
  - platform: time
    at: !input start_time
    id: "start_trigger"
  - platform: time
    at: !input end_time
    id: "end_trigger"
    

    
action:
  - service: media_player.volume_set
    data:
      volume_level: 0.69
    target:
      entity_id: !input speaker_target
  - service: media_player.play_media
    target:
      entity_id: !input speaker_target
    data:
      media_content_id: >-
        spotify://122feef405d4590fc781e97d48a03eff/spotify:playlist:37i9dQZEVXbJNSeeHswcKB
      media_content_type: spotify://playlist
    metadata:
      title: Top 50 - België
      thumbnail: >-
        https://charts-images.scdn.co/assets/locale_en/regional/daily/region_be_large.jpg
      media_class: playlist
      children_media_class: track
      navigateIds:
        - {}
        - media_content_type: spotify://library
          media_content_id: spotify://122feef405d4590fc781e97d48a03eff
        - media_content_type: spotify://current_user_playlists
          media_content_id: spotify://122feef405d4590fc781e97d48a03eff/current_user_playlists
        - media_content_type: spotify://playlist
          media_content_id: >-
            spotify://122feef405d4590fc781e97d48a03eff/spotify:playlist:37i9dQZEVXbJNSeeHswcKB
  
